# syntax=docker/dockerfile:1

FROM python:3.13-slim-trixie

LABEL org.opencontainers.image.title="Reikun" \
      org.opencontainers.image.description="例訓 (れいくん) - Japanese Sentence-Mining & Kanji Assistant" \
      org.opencontainers.image.source="https://github.com/AnkS4/Reikun"

# PYTHONDONTWRITEBYTECODE: nothing should write .pyc at *runtime* — everything
# importable is precompiled at build time (UV_COMPILE_BYTECODE for deps,
# compileall for our own source).
# UV_PYTHON_DOWNLOADS=never: use the base image's interpreter. Without this uv
# would silently download a standalone CPython (~30 MB into the image) if
# discovery ever fails, e.g. after a base bump or a requires-python change —
# this turns that regression into a build error instead.
# INGEST_VIA_DOCKER — one flag for both halves of the pipeline. As a build
# arg, =1 installs rsync (download_edrdg.py) and the dev dep group
# (wordfreq/mecab for build_chunks.py, ~110 MB); the ENV line below bakes
# the same value into the image so the container *also runs* the pipeline
# at boot (scripts/startup.py reads it). Default 0: lean runtime-only image
# that just serves — `docker build --build-arg INGEST_VIA_DOCKER=1 .` for
# self-provisioning.
ARG INGEST_VIA_DOCKER=0
ENV INGEST_VIA_DOCKER=$INGEST_VIA_DOCKER

# UV_LINK_MODE=copy: the uv cache mount and /app/.venv are different
# filesystems, so hardlinking can't work; say so rather than warn every build.
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    MODELS_DIR=/app/models/fastembed \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PYTHON_DOWNLOADS=never \
    UV_CACHE_DIR=/home/app/.cache/uv

# Run as an unprivileged user. UID 1000 matches the default first user on most
# Linux hosts, so the docker-compose bind mounts (./data) stay writable without
# chown. Switching USER *before* the install steps means everything under /app
# is created with the right owner — no `chown -R` layer duplicating the ~600 MB
# venv.
RUN useradd --create-home --uid 1000 app \
    && mkdir /app && chown app:app /app \
    && if [ "$INGEST_VIA_DOCKER" = "1" ]; then \
         apt-get update \
         && apt-get install -y --no-install-recommends rsync \
         && rm -rf /var/lib/apt/lists/*; \
       fi
USER app
WORKDIR /app

# Install python dependencies into /app/.venv, frozen from uv.lock.
# --no-dev keeps the ingest-only dev group (wordfreq/mecab/ipadic) out of the
# default image; INGEST_VIA_DOCKER=1 syncs them in. --no-install-project
# skips building the app package itself so this layer is cached until the
# lockfile changes, not on every code edit.
#
# uv is *mounted*, not copied: it is a build-only tool, and COPYing the binary
# would add ~56 MB to the runtime image for no benefit.
# The cache mount keeps downloaded wheels on the build host across rebuilds
# without ever committing them to a layer (which is what --no-cache used to
# prevent, at the cost of re-downloading everything each time).
COPY --chown=app:app pyproject.toml uv.lock ./
RUN --mount=from=ghcr.io/astral-sh/uv:0.12.17,source=/uv,target=/usr/local/bin/uv \
    --mount=type=cache,target=/home/app/.cache/uv,uid=1000,gid=1000 \
    if [ "$INGEST_VIA_DOCKER" = "1" ]; then \
      uv sync --frozen --no-install-project; \
    else \
      uv sync --frozen --no-dev --no-install-project; \
    fi
ENV PATH="/app/.venv/bin:$PATH"

# Copy application source code, then install the project itself (editable) —
# puts `app`/`scripts` on sys.path and generates the `reikun` console script.
COPY --chown=app:app app/ app/
COPY --chown=app:app scripts/ scripts/
RUN --mount=from=ghcr.io/astral-sh/uv:0.12.17,source=/uv,target=/usr/local/bin/uv \
    --mount=type=cache,target=/home/app/.cache/uv,uid=1000,gid=1000 \
    if [ "$INGEST_VIA_DOCKER" = "1" ]; then \
      uv sync --frozen; \
    else \
      uv sync --frozen --no-dev; \
    fi

# kanji_table.json is needed by the app at runtime and is small enough (~5 MB)
# to ship in the image; it is committed to the repo (generated by
# scripts/build_chunks.py). chunks.json is not shipped — it is only needed for
# the one-time ingest, which runs outside the container host on free tiers.
COPY --chown=app:app data/processed/kanji_table.json data/processed/kanji_table.json

# Pre-download the embedding/sparse ONNX models into the image so the first
# request doesn't pay the download cost. Importing app.embedder pulls in
# app.config, which creates models/ and the data/ subdirectories as a side
# effect — hence no explicit mkdir here.
# compileall: uv only precompiles dependencies, not the editable project, so
# without this our own modules are re-parsed on every container start.
RUN python -c "from app.embedder import warm_models; warm_models()" \
    && python -m compileall -q app scripts

EXPOSE 8501

# /_stcore/health is Streamlit's health endpoint and returns a literal "ok".
# Do not be tempted by a friendlier-looking path: Streamlit's SPA catch-all
# serves index.html with HTTP 200 for *any* unmatched route, so a probe against
# e.g. /healthz passes unconditionally and tests nothing.
# start-period is generous because scripts/startup.py may run the whole
# download -> build -> ingest pipeline before Streamlit ever binds the port.
HEALTHCHECK --interval=60s --timeout=5s --start-period=10m --retries=3 \
    CMD python -c "import httpx,sys,os; r=httpx.get(f\"http://localhost:{os.getenv('PORT','8501')}/_stcore/health\", timeout=3); sys.exit(0 if r.status_code==200 and r.text.strip()=='ok' else 1)"

CMD ["reikun"]
