/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only — the process is up. Dependencies are checked by /ready.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: a real query against the Qdrant collection.
         *     503 when Qdrant is unreachable or the collection is missing/empty.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Endpoint
         * @description Same pipeline as the dictionary UI: rewrite → route → retrieve.
         *     Results carry `ruby` parts for furigana rendering; Japanese sentences that
         *     decompose into word units come back in `segments` (the "parsed as" chips).
         */
        get: operations["search_endpoint_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kanji/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kanji Random Endpoint
         * @description A random kanji that is itself a JMdict headword — the shuffle button's
         *     pick. Same rules as the UI: frequency-ranked pool, optionally restricted
         *     to a JLPT level, up to 8 headword-verified tries then an unchecked pick.
         */
        get: operations["kanji_random_endpoint_kanji_random_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kanji": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kanji Batch Endpoint
         * @description Compact hover-card data for several kanji at once — one round-trip per
         *     sentence of tooltips. Unknown kanji map to null.
         */
        get: operations["kanji_batch_endpoint_kanji_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kanji/{char}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kanji Endpoint
         * @description KANJIDIC2 details (meta badges, readings with okurigana parts, common
         *     words with ruby parts) for one kanji — the frontend renders the card.
         */
        get: operations["kanji_endpoint_kanji__char__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain Endpoint
         * @description JLPT-level-calibrated grammar explanation (Groq). Markdown bullets.
         */
        post: operations["explain_endpoint_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explain/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain Stream Endpoint
         * @description Server-sent events: `data: {"text": "…"}` chunks as Groq streams them,
         *     then `data: {"done": true, "explanation_id": …, "latency_ms": …}`.
         */
        post: operations["explain_stream_endpoint_explain_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Feedback Endpoint
         * @description Thumbs up (+1) / down (-1) on a search or an explanation.
         */
        post: operations["feedback_endpoint_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CommonWord */
        CommonWord: {
            /** Kanji Form */
            kanji_form?: string | null;
            /**
             * Reading
             * @default
             */
            reading: string;
            /**
             * Meanings
             * @default []
             */
            meanings: string[];
            /**
             * Gloss
             * @default
             */
            gloss: string;
            /**
             * Ruby
             * @default []
             */
            ruby: components["schemas"]["RubyPart"][];
        };
        /**
         * ErrorResponse
         * @description FastAPI's HTTPException body — declared so non-422 errors show up in the schema.
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** ExampleSentence */
        ExampleSentence: {
            /** Japanese */
            japanese: string;
            /**
             * English
             * @default
             */
            english: string;
        };
        /** ExplainRequest */
        ExplainRequest: {
            /**
             * Sentence
             * @description Japanese example sentence
             */
            sentence: string;
            /**
             * English
             * @description English translation (improves the explanation)
             * @default
             */
            english: string;
            /**
             * Level
             * @default N5
             * @enum {string}
             */
            level: "N5" | "N4" | "N3" | "N2" | "N1";
        };
        /** ExplainResponse */
        ExplainResponse: {
            /** Explanation Id */
            explanation_id?: number | null;
            /** Level */
            level: string;
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
            /** Text */
            text: string;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "search" | "explanation";
            /**
             * Ref Id
             * @description `search_id` from /search or `explanation_id` from /explain
             */
            ref_id?: number | null;
            /**
             * Rating
             * @enum {integer}
             */
            rating: 1 | -1;
            /** Query */
            query?: string | null;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Feedback Id */
            feedback_id?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** KanjiCard */
        KanjiCard: {
            /** Literal */
            literal?: string | null;
            /** Codepoint Hex */
            codepoint_hex?: string | null;
            /** Stroke Count */
            stroke_count?: number | null;
            /** Grade */
            grade?: number | null;
            /** Freq */
            freq?: number | null;
            /** Jlpt Level */
            jlpt_level?: number | null;
            /**
             * Meanings
             * @default []
             */
            meanings: string[];
            /**
             * Meta
             * @default []
             */
            meta: components["schemas"]["MetaBadge"][];
            /**
             * On Yomi
             * @default []
             */
            on_yomi: string[];
            /**
             * Kun Yomi
             * @default []
             */
            kun_yomi: string[];
            /**
             * Readings
             * @default {}
             */
            readings: {
                [key: string]: components["schemas"]["ReadingChip"][];
            };
            /**
             * Common Words
             * @default []
             */
            common_words: components["schemas"]["CommonWord"][];
            stroke?: components["schemas"]["StrokeData"] | null;
        };
        /**
         * KanjiHover
         * @description Compact card for kanji-in-text hover tooltips (batch endpoint).
         */
        KanjiHover: {
            /** Literal */
            literal: string;
            /**
             * Meanings
             * @default []
             */
            meanings: string[];
            /**
             * On Yomi
             * @default []
             */
            on_yomi: string[];
            /**
             * Kun Yomi
             * @default []
             */
            kun_yomi: string[];
            /**
             * Meta
             * @default []
             */
            meta: components["schemas"]["MetaBadge"][];
        };
        /** MetaBadge */
        MetaBadge: {
            /** Label */
            label: string;
            /** Tip */
            tip: string;
        };
        /** RandomKanji */
        RandomKanji: {
            /** Kanji */
            kanji: string;
        };
        /**
         * ReadingChip
         * @description One on/kun reading; `okurigana` is the part after KANJIDIC2's dot (た.べる).
         */
        ReadingChip: {
            /** Stem */
            stem: string;
            /** Okurigana */
            okurigana?: string | null;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Status
             * @default ready
             * @constant
             */
            status: "ready";
            /** Collection */
            collection: string;
            /** Entries */
            entries: number;
            /** Llm */
            llm: string;
        };
        /** RewriteInfo */
        RewriteInfo: {
            /** Original */
            original: string;
            /** Query */
            query: string;
            /** Method */
            method: string;
            /** Changed */
            changed: boolean;
        };
        /**
         * RubyPart
         * @description One display segment of a headword: `rt` carries the furigana when set.
         */
        RubyPart: {
            /** Text */
            text: string;
            /** Rt */
            rt?: string | null;
        };
        /**
         * SearchMeta
         * @description Per-request diagnostics. `route` is set in auto mode. On a cache hit
         *     the timing fields describe the original computation; on a `too_long`
         *     rejection they are absent — the pipeline never ran.
         */
        SearchMeta: {
            /** Route */
            route?: ("ja" | "en_word" | "en_sentence") | null;
            /** Rewrite Ms */
            rewrite_ms?: number | null;
            /** Embed Ms */
            embed_ms?: number | null;
            /** Retrieve Ms */
            retrieve_ms?: number | null;
            /** Segment Ms */
            segment_ms?: number | null;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /**
             * Too Long
             * @description The character cap the query exceeded
             */
            too_long?: number | null;
        };
        /** SearchResponseModel */
        SearchResponseModel: {
            /** Search Id */
            search_id?: number | null;
            /** Results */
            results: components["schemas"]["SearchResult"][];
            rewrite: components["schemas"]["RewriteInfo"];
            /** Mode */
            mode: string;
            /** Latency Ms */
            latency_ms: number;
            /** Segments */
            segments?: components["schemas"]["Segment"][] | null;
            /**
             * @default {
             *       "cached": false
             *     }
             */
            meta: components["schemas"]["SearchMeta"];
        };
        /** SearchResult */
        SearchResult: {
            /** Id */
            id: number | null;
            /** Kanji Form */
            kanji_form?: string | null;
            /**
             * Reading
             * @default
             */
            reading: string;
            /**
             * Kanji Forms
             * @default []
             */
            kanji_forms: string[];
            /**
             * Readings
             * @default []
             */
            readings: string[];
            /**
             * Meanings
             * @default []
             */
            meanings: string[];
            /**
             * Example Sentences
             * @default []
             */
            example_sentences: components["schemas"]["ExampleSentence"][];
            /**
             * Is Common
             * @default false
             */
            is_common: boolean;
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Score
             * @default 0
             */
            score: number;
            /**
             * Ruby
             * @default []
             */
            ruby: components["schemas"]["RubyPart"][];
        };
        /**
         * Segment
         * @description One word unit of a parsed Japanese sentence (a chip).
         */
        Segment: {
            /** Text */
            text: string;
            /** Kanji Form */
            kanji_form?: string | null;
            /**
             * Reading
             * @default
             */
            reading: string;
            /**
             * Meanings
             * @default []
             */
            meanings: string[];
            /**
             * Gloss
             * @default
             */
            gloss: string;
            /**
             * Ruby
             * @default []
             */
            ruby: components["schemas"]["RubyPart"][];
            /**
             * Options
             * @default []
             */
            options: string[];
            /**
             * Approx
             * @default false
             */
            approx: boolean;
        };
        /**
         * StrokeData
         * @description KanjiVG stroke order as sanitized data — the frontend draws the SVG.
         */
        StrokeData: {
            /** View Box */
            view_box: string;
            /** Strokes */
            strokes: string[];
            /** Numbers */
            numbers: components["schemas"]["StrokeNumber"][];
        };
        /** StrokeNumber */
        StrokeNumber: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Value */
            value: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Qdrant unreachable, or the collection is missing/empty */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_endpoint_search_get: {
        parameters: {
            query: {
                /** @description English or Japanese word, or a natural-language question */
                q: string;
                /** @description Number of results */
                n?: number;
                /** @description auto routes the query to the best plan; the rest are fixed pipelines */
                mode?: "auto" | "hybrid" | "vector" | "text";
                /** @description Normalise natural-language queries to a dictionary gloss first */
                rewrite?: boolean;
                /** @description Record the search in the telemetry sink */
                log?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kanji_random_endpoint_kanji_random_get: {
        parameters: {
            query?: {
                /** @description Prefer kanji tagged at this JLPT level (falls back to the common pool) */
                level?: ("N5" | "N4" | "N3" | "N2" | "N1") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RandomKanji"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kanji_batch_endpoint_kanji_get: {
        parameters: {
            query: {
                /** @description Kanji characters to look up (deduped; every char is treated as one kanji) */
                chars: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["KanjiHover"] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kanji_endpoint_kanji__char__get: {
        parameters: {
            query?: {
                /** @description Include KanjiVG stroke order as structured data (viewBox, path d's, number labels) */
                strokes?: boolean;
                log?: boolean;
            };
            header?: never;
            path: {
                char: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KanjiCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_endpoint_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_stream_endpoint_explain_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_endpoint_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
